#!/usr/bin/env bash
name="linux-base"
version="4.9"
description="Linux image base package"
source="https://salsa.debian.org/kernel-team/linux-base/-/archive/${version}/linux-base-${version}.tar.gz"
depends=""
builddepend=""
groups="sys.base"


setup(){
    echo ""
}

build(){
	cd $SOURCEDIR
	echo "dizin" 
	pwd
    make
}

package(){
    make install DESTDIR=$DESTDIR
}
