#!/usr/bin/env bash
name="perl-archive-zip"
version="1.68"
description="Provide a perl interface to ZIP archive files"
source="https://search.cpan.org/CPAN/authors/id/P/PH/PHRED/Archive-Zip-${version}.tar.gz"
depends="perl"
builddepend=""
groups="dev.perl"


setup(){
	cd $SOURCEDIR
    perl Makefile.PL INSTALLDIRS=vendor

}

build(){
	make
}

package(){
	make DESTDIR="$DESTDIR" install
}
