#!/usr/bin/env bash
name="perl-module-build"
version="0.4234"
description="Build, test, and install Perl modules"
source="https://search.cpan.org/CPAN/authors/id/L/LE/LEONT/Module-Build-$version.tar.gz"
depends="perl,perl-inc-latest"
builddepend="perl-par-dist,perl-archive-zip"
groups="dev.perl"


setup(){
	cd $SOURCEDIR
    perl Build.PL installdirs=vendor
}

build(){
	perl Build
}

package(){
	perl Build install destdir="$DESTDIR"
}
