#!/usr/bin/env bash
name="perl-par-dist"
version="0.52"
description="Perl bindings to create and manipulate PAR distributions"
source="https://search.cpan.org/CPAN/authors/id/R/RS/RSCHUPP/PAR-Dist-$version.tar.gz"
depends="perl"
builddepend=""
groups="dev.perl"


setup(){
	cd $SOURCEDIR
    PERL_MM_USE_DEFAULT=1 perl Makefile.PL INSTALLDIRS=vendor

}

build(){
	make
}

package(){
	make DESTDIR="$DESTDIR" install
}
