#!/usr/bin/env bash
name="elementary-icon-theme"
version="8.0.0"
description="Named, vector icons for elementary OS"
source="https://github.com/elementary/icons/archive/refs/tags/$version.tar.gz"
depends="hicolor-icon-theme"
builddepend="meson"
group="x11.themes"

setup(){
    cd $SOURCEDIR
    meson setup $BUILDDIR \
        --prefix=/usr \
        --libdir=/usr/lib64 \
        -Dvolume_icons=false \
        -Ddefault_library=both
}
build(){
    meson compile -C $BUILDDIR
}

package(){
    DESTDIR="$DESTDIR" meson install -C $BUILDDIR
}
