#!/usr/bin/env bash
name="perl-xs-parse-keyword"
version="0.42"
description="XS functions to assist in parsing keyword syntax"
source="https://cpan.metacpan.org/authors/id/P/PE/PEVANS/XS-Parse-Keyword-$version.tar.gz"
depends="perl"
builddepend="perl-module-build,perl-extutils-cchecker"
groups="dev.perl"


setup(){
	cd $SOURCEDIR
    export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
	perl Build.PL \
		--installdirs=vendor \
		--create_packlist=0

}

build(){
	./Build
}

package(){
	./Build install --destdir="$DESTDIR"
}
