#!/usr/bin/env bash
name="perl-inc-latest"
version="0.500"
description="Build, test, and install Perl modules"
source="https://search.cpan.org/CPAN/authors/id/D/DA/DAGOLDEN/inc-latest-$version.tar.gz"
depends="perl"
builddepend=""
groups="dev.perl"


setup(){
	cd $SOURCEDIR
    perl Makefile.PL INSTALLDIRS=vendor

}

build(){
	make
}

package(){
	make DESTDIR="$DESTDIR" install
}
