#!/usr/bin/env bash
name="perl-pod-parser"
version="1.67"
description="Modules for parsing/translating POD format documents"
source="https://cpan.metacpan.org/authors/id/M/MA/MAREKR/Pod-Parser-$version.tar.gz"
depends="perl"
builddepend=""
groups="dev.perl"


setup(){
	cd $SOURCEDIR
    perl Makefile.PL INSTALLDIRS=vendor
}

build(){
	make
}

package(){
	make DESTDIR="$DESTDIR" install
}
