#!/usr/bin/env bash
name="perl-extutils-cchecker"
version="0.12"
description="Perl module configuration-time utilities for using C headers, libraries, or OS features"
source="https://cpan.metacpan.org/authors/id/P/PE/PEVANS/ExtUtils-CChecker-$version.tar.gz"
depends="perl"
builddepend="perl-module-build"
groups="dev.perl"


setup(){
	cd $SOURCEDIR
    export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
	perl Build.PL \
		--installdirs=vendor \
		--create_packlist=0

}

build(){
	./Build
}

package(){
	./Build install --destdir="$DESTDIR"
}
