#!/usr/bin/env bash
name="perl-syntax-keyword-try"
version="0.29"
description="a try/catch/finally syntax for perl"
source="https://cpan.metacpan.org/authors/id/P/PE/PEVANS/Syntax-Keyword-Try-$version.tar.gz"
depends="perl,perl-xs-parse-keyword"
builddepend="perl-module-build"
groups="dev.perl"


setup(){
	cd $SOURCEDIR
    export CFLAGS=$(perl -MConfig -E 'say $Config{ccflags}')
	perl Build.PL \
		--installdirs=vendor \
		--create_packlist=0

}

build(){
	./Build
}

package(){
	./Build install --destdir="$DESTDIR"
}
